// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcY4xQCHXpWiZ8qJULkhbQJSoEMjcvdkI',
    appId: '1:786699485546:web:fbfba55e4b546736202513',
    messagingSenderId: '786699485546',
    projectId: 'multiservice-aa4e9',
    authDomain: 'multiservice-aa4e9.firebaseapp.com',
    storageBucket: 'multiservice-aa4e9.appspot.com',
    measurementId: 'G-ECF206ZGC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANMid5S8yz0TfDVLubWGjjPmihOIgiYyU',
    appId: '1:786699485546:android:b94ca05651b81d1e202513',
    messagingSenderId: '786699485546',
    projectId: 'multiservice-aa4e9',
    storageBucket: 'multiservice-aa4e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmHIMqraMR-_g_wJWO1nxrR23WpCPgYf8',
    appId: '1:786699485546:ios:b3aa85cb2b91de2a202513',
    messagingSenderId: '786699485546',
    projectId: 'multiservice-aa4e9',
    storageBucket: 'multiservice-aa4e9.appspot.com',
    iosBundleId: 'com.example.multiservice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmHIMqraMR-_g_wJWO1nxrR23WpCPgYf8',
    appId: '1:786699485546:ios:ea68d00cfc74b32f202513',
    messagingSenderId: '786699485546',
    projectId: 'multiservice-aa4e9',
    storageBucket: 'multiservice-aa4e9.appspot.com',
    iosBundleId: 'com.example.multiservice.RunnerTests',
  );
}
